Repository ansible-collections/community.grafana, pull requests merged in 2019-12, with the labels that each got.

#14 (Hopefully) allow non-Admins to commit
  .github/settings.yml
Labels: PR: unreviewed

#16 grafana_dashboard: state isn't required as we have a default
  plugins/modules/grafana_dashboard.py
Labels: PR: reviewed-approved

#17 ds_type is required in spec
  plugins/modules/grafana_datasource.py
Labels: PR: reviewed-approved

#15 CI to use ansible-minimal
  .github/workflows/ansible-test.yml
Labels: PR: unreviewed, feature

#24 Add Code Coverage badge
  README.md
Labels: PR: reviewed-approved

#26 feature(grafana_annotations): add hostname to tags
  plugins/callback/grafana_annotations.py
Labels: PR: reviewed-approved

#27 Add a badge providing CI status on master
  README.md
Labels: PR: reviewed-approved

#29 Update galaxy.yml for 0.1.0 release
  galaxy.yml
Labels: PR: reviewed-approved

#31 Fixing sanity tests errors detected on master
  tests/integration/targets/grafana_datasource/tasks/thruk.yml
Labels: PR: reviewed-approved
