Repository ansible-collections/community.grafana, pull requests merged in 2020-03, with the labels that each got.

#68 Fix test on attributes presence in the datasource
  plugins/modules/grafana_datasource.py
Labels: PR: reviewed-approved

#71 Port ansible-collection-migration diff
  plugins/callback/grafana_annotations.py
  plugins/lookup/grafana_dashboard.py
  tests/sanity/ignore-2.9.txt
Labels: PR: reviewed-approved

#70 Release v0.2.1
  CHANGELOG.md
  galaxy.yml
Labels: PR: reviewed-approved

#75 CI should use devel
  .github/workflows/ansible-test.yml
Labels: PR: reviewed-approved

#79 Support special chars in folder name fix #78
  plugins/modules/grafana_folder.py
Labels: PR: reviewed-approved

#77 dashboard: fix issue during import
  plugins/modules/grafana_dashboard.py
Labels: PR: reviewed-changes-requested

#82 remove meta key if exists for compare
  plugins/modules/grafana_dashboard.py
Labels: PR: partially-approved

#81 Release 0.2.2
  CHANGELOG.md
  galaxy.yml
Labels: PR: reviewed-approved
