Repository ansible-collections/community.grafana, pull requests merged in 2021-04, with the labels that each got.

#161 Release v1.2.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/1.2.1.yml
  galaxy.yml
Labels: PR: unreviewed

#165 Update some readme links
  README.md
Labels: PR: partially-approved

#167 Fix extraction of the error message on update of a dashboard
  plugins/modules/grafana_dashboard.py
Labels: PR: partially-approved

#166 dashboard: Fail if the target directory does not exist
  changelogs/fragments/1.2.2.yml
  plugins/modules/grafana_dashboard.py
  tests/integration/targets/grafana_dashboard/tasks/dashboard-folder-destination.yml
  tests/integration/targets/grafana_dashboard/tasks/main.yml
Labels: PR: partially-approved

#169 grafana_team: unable to use spaces or other utf-8 chars in name/title
  changelogs/fragments/1.2.2.yml
  plugins/modules/grafana_team.py
Labels: PR: reviewed-approved

#158 grafana_dashboard lookup: fix passing API key
  changelogs/fragments/158-grafana_dashboard-lookup-api-key.yml
  plugins/lookup/grafana_dashboard.py
Labels: PR: partially-approved
